Repository strongloop/loopback, pull requests merged in 2019-01, with the labels that each got.

#4107 Update underscore.string to 3.3.5
  package.json
Labels: security

#4108 Fix crash when modifying a user with an unknown id
  common/models/user.js
  test/user.integration.js
Labels: bug, community contribution, critical

#4111 Fix crash when modifying an unknown user [2.x]
  common/models/user.js
  test/user.integration.js
Labels: bug, critical
